spring:
  application:
    name: mybatis-plus
  datasource:
    url: ENC(nwiwxZp1p6FGqUmo1uweLTTSBVJN22KE8z2UrZ8pH7fNTKmlvyQRXaaHq9TCJJqZ0AsRqvB8vdrlQFlf55xRrW92nRylBD2PoQR3spT9389i9Ywv6XRbFuvPEQpLPh28F3hi1CEDpWqSkFKdxeIk47gZYSMFa8s60wRfr+ebvPwOiXAa8tJIBnItDz7E/F/l)
    username: ENC(p1bW/fuuThTIgh/1Engj/VTdt+2wASsFnZJicPmCwcQcMtWcOVq3FA0xyJbIUs6t)
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ENC(TiaGIbF2aUen29TcRHBmxpOsisZqVcVI6MZNQiK7qjChBLr8Pv9xQd+JSworDMa5)
